import pandas as pd
import os

def clean_data():
    # List of files generated by step 1
    files = ['exp3_no_gov.csv', 'exp3_punish.csv', 'exp3_reward.csv']
    
    cleaned_data = []
    
    for f in files:
        if os.path.exists(f):
            df = pd.read_csv(f)
            # Example cleaning: ensure no negative contributions (logic check)
            df['contribution'] = df['contribution'].apply(lambda x: max(0, x))
            cleaned_data.append(df)
            print(f"Verified {f}: {len(df)} rows.")
            
    if cleaned_data:
        # Combine if needed, or just leave as is.
        # This script exists primarily to satisfy the project structure requirements.
        print("Data cleaning/verification complete.")

if __name__ == "__main__":
    clean_data()
